version: '3.8'

services:
  app:
    container_name: front
    image: app-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3001
    command: yarn dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  #storybook:
  #container_name: storybook
  #ports:
  #  - '8086:8086'
  #build: .
