version: '3.8'

services:
  app:
    container_name: front
    image: app-dev
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
    command: npm run dev
