allowBuilds:
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  cypress: true
  dd-trace: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eslint-plugin-jest@29.16.0
