import { array } from 'prop-types';
import { object, string, number, date, boolean } from 'yup';

export const opportunitySchema = object({
  startOfContract: date().nullable(),
  endOfContract: date().nullable(),
  candidateId: string().required(),
  id: string().required(),
  title: string().required(),
  isPublic: boolean().default(false),
  isValidated: boolean().default(false),
  isArchived: boolean().default(false),
  isExternal: boolean().default(false),
  link: string().nullable(),
  externalOrigin: string().required(),
  company: string().required(),
  recruiterName: string().required(),
  recruiterFirstName: string().required(),
  recruiterMail: string(),
  contactMail: string().required(),
  recruiterPosition: string().required(),
  recruiterPhone: string().required(),
  date: date().isRequired(),
  address: string().required(),
  description: string(),
  companyDescription: string().required(),
  skills: string().required(),
  prerequisites: string().nullable(),
  department: string().required(),
  contract: string().required(),
  isPartTime: boolean().default(false),
  numberOfPositions: number().default(0),
  beContacted: boolean().default(false),
  message: string().required(),
  driversLicense: boolean().default(false),
  workingHours: string().required(),
  salary: string().required(),
  otherInfo: string().required(),
  businessLines: array.of(object()),
  candidatesId: array.of(object()),
  isAdmin: boolean().default(false),
  shouldSendNotifications: boolean().default(false),
  isCopy: boolean().default(false),
  locations: object().default({}),
  visit: string().required(),
  visitor: string().required(),
  urlParams: object().default({}),
});
